module Vorspiel.Prelude
  ( module Prelude,
    module Numeric.Natural,
    module Data.Function,
    module Data.Foldable,
    module Data.Monoid,
    module Data.List.NonEmpty,
    module Data.Void,
  )
where

import Data.Foldable (foldMap')
import Data.Function (on, (&))
import Data.List.NonEmpty (NonEmpty (..))
import Data.Monoid (Product (..), Sum (..))
import Data.Void (Void)
import Numeric.Natural (Natural)
import Prelude
  ( Applicative (..),
    Bool (..),
    Bounded (..),
    Char,
    Double,
    Either (..),
    Enum,
    Eq (..),
    Float,
    Floating (..),
    Foldable (foldMap, foldl, foldr),
    Fractional (..),
    Functor (..),
    IO,
    Int,
    Integer,
    Integral (..),
    Maybe (..),
    Monad (..),
    Monoid (mempty),
    Num (..),
    Ord (..),
    Ordering (..),
    Rational,
    Real (..),
    RealFloat (..),
    RealFrac (..),
    Semigroup (..),
    Show (..),
    String,
    Word,
    const,
    curry,
    either,
    even,
    flip,
    fromIntegral,
    gcd,
    id,
    lcm,
    maybe,
    not,
    odd,
    otherwise,
    realToFrac,
    seq,
    subtract,
    uncurry,
    ($),
    ($!),
    (&&),
    (++),
    (.),
    (<$>),
    (^),
    (^^),
    (||),
  )
